name: 'Delete Completed Branches'
description: 'Delete all branches that are merged into master'
inputs:
  master-name:
    description: 'Name of master branch'
    required: true
  expired-time:
    description: 'Expired Time (day)'
    required: true
    default: 30
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.master-name }}
    - ${{ inputs.expired-time }}
