on:
  push:
    branches:
      - master

jobs:
  clean_branches:
    runs-on: ubuntu-latest
    name: Clean old branches
    steps:
    - name: Clean old branches with acions
      id: search_and_delete
      uses: longht021189/github_actions-delete_completed_branches@0.0.2
      with:
        master-name: 'master'
        expired-time: 31

