on:
  push:
    branches:
      - master

jobs:
  clean_branches:
    runs-on: ubuntu-latest
    name: Clean old branches
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Clean old branches with acions
      id: search_and_delete
      uses: ./
      # with:
      #   github-token: ${{github.token}}
      #   master-name: 'master'
      #   expired-time: 31

    # - name: Get the output time
    #   run: echo "The time was ${{ steps.search_and_delete.outputs.time }}"
